name = "woodlandspark"
compatibility_date = "2026-05-30"
pages_build_output_dir = "dist"

[vars]
APP_ENV = "production"
PRODUCTION_URL = "https://woodlandspark.shubodaya.dev"
SESSION_COOKIE = "woodlands_session"
SESSION_DAYS = "7"
MEDIA_PUBLIC_BASE = "/media"

[[d1_databases]]
binding = "DB"
database_name = "woodlandspark-db"
database_id = "f810ce67-2b84-46d4-8da0-5b7b01f028df"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "woodlandspark-media"
